[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "chatbotsclient"
version = "1.0.2"
dependencies = ["pusher", "pysher", "spacy", "Flask", "Flask-Cors"]